// Decorative depth only: content and controls remain in normal document flow.
(() => {
 const root=document.documentElement,reduced=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover:hover) and (pointer:fine)');
 const surfaces=[...document.querySelectorAll('.portrait-frame,.language-card,.interest-visual')],animations=new Set();
 const stopped=()=>reduced.matches||document.hidden||root.classList.contains('motion-paused');
 const reset=element=>{element.style.removeProperty('--tilt-x');element.style.removeProperty('--tilt-y');element.style.removeProperty('--depth-light');delete element.dataset.tilting;};
 let frame=0,pending=null,current=null,bounds=null;
 const flush=()=>{frame=0;if(!pending||stopped())return;const {element,x,y}=pending;element.style.setProperty('--tilt-x',`${-y*4}deg`);element.style.setProperty('--tilt-y',`${x*4}deg`);element.style.setProperty('--depth-light','.8');};
 const cancel=()=>{if(frame)cancelAnimationFrame(frame);frame=0;pending=null;current=null;bounds=null;surfaces.forEach(reset);for(const animation of animations)animation.cancel();animations.clear();};
 const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting){reset(entry.target);continue;}const element=entry.target;if(stopped()||element.dataset.depthEntered)continue;element.dataset.depthEntered='true';const animation=element.animate([{transform:'perspective(900px) rotateX(8deg) translateY(18px)'},{transform:'perspective(900px) rotateX(0deg) translateY(0)'}],{duration:850,easing:'cubic-bezier(.2,.7,.2,1)'});animations.add(animation);animation.finished.then(()=>animations.delete(animation)).catch(()=>animations.delete(animation));}},{threshold:.15});
 for(const element of surfaces){element.classList.add('depth-surface');observer.observe(element);element.addEventListener('pointerenter',()=>{if(stopped()||!fine.matches)return;current=element;bounds=element.getBoundingClientRect();element.dataset.tilting='true';});element.addEventListener('pointermove',event=>{if(current!==element||!bounds||stopped())return;pending={element,x:Math.max(-1,Math.min(1,(event.clientX-bounds.left)/bounds.width*2-1)),y:Math.max(-1,Math.min(1,(event.clientY-bounds.top)/bounds.height*2-1))};if(!frame)frame=requestAnimationFrame(flush);});element.addEventListener('pointerleave',()=>{if(current===element){current=null;pending=null;}reset(element);});}
 document.addEventListener('visibilitychange',()=>{if(stopped())cancel();});reduced.addEventListener('change',cancel);new MutationObserver(()=>{if(stopped())cancel();}).observe(root,{attributes:true,attributeFilter:['class']});window.addEventListener('scroll',()=>{if(current){reset(current);current=null;pending=null;}},{passive:true});window.addEventListener('blur',cancel);window.addEventListener('pagehide',cancel);
})();
