import React, {createContext, memo, useContext, useEffect, useRef, useState, type ReactNode} from 'react';
import {LazyMotion, domAnimation, m, useAnimationControls, useInView, useMotionValue, useScroll, useSpring, useTransform, type MotionValue} from 'framer-motion';
import {ArrowDown, ArrowUpRight, Layers3, Workflow, Box, Orbit, Pause, Play} from 'lucide-react';
import content from './content.json';
import journey from './journey.json';
import toolkit from '../hero-toolkit.json';
import {MethodSection, InternationalSection, BeyondSection} from './ExtensionSections';

const Preferences=createContext({fr:false,stopped:false});
function PreferencesProvider({children}:{children:ReactNode}) {
 const [value,setValue]=useState({fr:false,stopped:false});
 useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{const next={fr:document.documentElement.lang==='fr',stopped:reduced.matches||document.documentElement.classList.contains('motion-paused')||document.hidden};setValue(previous=>previous.fr===next.fr&&previous.stopped===next.stopped?previous:next);};const observer=new MutationObserver(update);observer.observe(document.documentElement,{attributes:true,attributeFilter:['lang','class']});reduced.addEventListener('change',update);document.addEventListener('visibilitychange',update);update();return()=>{observer.disconnect();reduced.removeEventListener('change',update);document.removeEventListener('visibilitychange',update);};},[]);
 return <Preferences.Provider value={value}>{children}</Preferences.Provider>;
}
function T({en,fr}:{en:string;fr:string}) {return <>{useContext(Preferences).fr?fr:en}</>;}
// These fragments are build-time, repository-owned semantic HTML, not user input.
const Native=memo(({html,className}:{html:string;className?:string})=><div className={className} dangerouslySetInnerHTML={{__html:html}}/>);
function FadeIn({children,delay=0,y=30,fade=true,className=''}:{children:ReactNode;delay?:number;y?:number;fade?:boolean;className?:string}) {
 const played=useRef(false);const ref=useRef<HTMLDivElement>(null),visible=useInView(ref,{once:true,margin:'50px'}),controls=useAnimationControls(),{stopped}=useContext(Preferences);
 useEffect(()=>{if(stopped){controls.stop();controls.set({opacity:1,y:0,rotateX:0});if(visible)played.current=true;return;}if(visible&&!played.current){played.current=true;controls.start({opacity:fade?[.92,1]:1,y:[y,0],rotateX:[6,0],transition:{duration:.7,delay,ease:[.25,.1,.25,1]}});}return()=>{controls.stop();controls.set({opacity:1,y:0,rotateX:0});};},[visible,stopped]);
 return <m.div ref={ref} initial={false} animate={controls} className={className} style={{transformPerspective:1000,transformOrigin:"50% 100%"}}>{children}</m.div>;
}
function ContactButton(){return <a className="contact-pill inline-flex items-center justify-center gap-4 rounded-full uppercase tracking-widest" href="#contact"><T en="Let's talk" fr="Discutons"/><ArrowUpRight size={19} aria-hidden="true"/></a>;}
function Header(){
 const [location,setLocation]=useState('');
 useEffect(()=>{const sections=[...document.querySelectorAll<HTMLElement>('#home,#showcase,#about,#services,#method,#work,#journey,#international,#beyond,#contact')];let observer:IntersectionObserver;const observe=()=>{observer?.disconnect();const visible=new Set<Element>();observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting)visible.add(entry.target);else visible.delete(entry.target);}setLocation(sections.filter(section=>visible.has(section)).slice(-1)[0]?.id||'');},{rootMargin:`-${Math.round(innerHeight*.15)}px 0px -${Math.round(innerHeight*.55)}px 0px`,threshold:0});sections.forEach(section=>observer.observe(section));};observe();window.addEventListener('resize',observe);return()=>{observer.disconnect();window.removeEventListener('resize',observe);};},[]);
 const group=location==='method'?'services':['international','beyond'].includes(location)?'about':location;
 const links=[['about','About','À propos'],['services','Expertise','Expertises'],['work','Projects','Projets'],['journey','Career','Parcours'],['contact','Contact','Contact']];
 const destinations=()=>links.map(([id,en,fr])=><a key={id} href={'#'+id} aria-current={group===id?'location':undefined}><T en={en} fr={fr}/></a>);
 return <><header className="site-header creator-header"><a href="#home" className="wordmark" aria-label="S.B — Saad Bayahia, home"><span className="identity-mark">S.B<span aria-hidden="true">↗</span></span><span className="identity-name">Saad Bayahia<small>Product Owner</small></span></a><nav className="desktop-nav" aria-label="Main navigation">{destinations()}</nav><div className="header-actions"><div className="language-switch" role="group" aria-label="Language / Langue"><button data-language="en" type="button" aria-pressed="true">EN</button><span aria-hidden="true">/</span><button data-language="fr" type="button" aria-pressed="false">FR</button></div><button className="motion-toggle" type="button" aria-label="Pause animations" aria-pressed="false" hidden><Pause className="pause-symbol" size={18}/><Play className="play-symbol" size={18}/></button><button className="menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="mobile-nav"><span/><span/></button></div></header><nav className="mobile-nav" id="mobile-nav" aria-label="Mobile navigation" hidden>{destinations()}</nav></>;
}
function Magnet({children}:{children:ReactNode}){
 const ref=useRef<HTMLDivElement>(null),{stopped}=useContext(Preferences),mx=useMotionValue(0),my=useMotionValue(0),x=useSpring(mx,{stiffness:90,damping:24}),y=useSpring(my,{stiffness:90,damping:24});
 useEffect(()=>{if(stopped){mx.set(0);my.set(0);return;}if(!matchMedia('(hover:hover) and (pointer:fine)').matches)return;let bounds:DOMRect|null=null;const measure=()=>{bounds=ref.current?.getBoundingClientRect()||null;};const move=(e:PointerEvent)=>{if(!bounds)return;const dx=e.clientX-(bounds.left+bounds.width/2),dy=e.clientY-(bounds.top+bounds.height/2);const active=Math.abs(dx)<bounds.width/2+150&&Math.abs(dy)<bounds.height/2+150;mx.set(active?Math.max(-24,Math.min(24,dx/12)):0);my.set(active?Math.max(-18,Math.min(18,dy/12)):0);};const reset=()=>{mx.set(0);my.set(0);};measure();window.addEventListener('pointermove',move,{passive:true});window.addEventListener('scroll',measure,{passive:true});window.addEventListener('resize',measure);window.addEventListener('blur',reset);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('scroll',measure);window.removeEventListener('resize',measure);window.removeEventListener('blur',reset);reset();};},[stopped]);
 return <m.div ref={ref} className="portrait-magnet" style={{x:stopped?0:x,y:stopped?0:y}}>{children}</m.div>;
}
function HeroSection(){
 const ref=useRef<HTMLDivElement>(null),actions=useRef<HTMLDivElement>(null),{stopped}=useContext(Preferences),{scrollYProgress}=useScroll({target:ref,offset:['start start','end end']}),zoom=useTransform(scrollYProgress,[0,.9],[0,1]);
 useEffect(()=>{const update=(value:number)=>{if(actions.current)actions.current.inert=!stopped&&value>=.6;};update(zoom.get());return zoom.on('change',update);},[zoom,stopped]);
 return <m.div className="creator-intro" style={{'--hero-zoom':stopped?0:zoom} as React.CSSProperties & {'--hero-zoom':number|MotionValue<number>}}><div ref={ref} className="hero-stage creator-hero-stage"><section id="home" className="hero creator-hero" aria-labelledby="hero-title"><div className="hero-scene-zoom"><Native html={content.heroArt}/><div className="hero-tool-fallback" aria-hidden="true">{["toolkit/shopify.svg","toolkit/n8n.svg","toolkit/hubspot.svg","toolkit/github.svg","hero-tools/python.svg","hero-tools/amazonaws.svg"].map((logo,i)=><img key={logo} src={"assets/"+logo} alt="" width="120" height="60" style={{"--tool-index":i} as React.CSSProperties}/>)}</div></div><div className="hero-shade" aria-hidden="true"/><div className="hero-title-layer"><FadeIn className="creator-hero-heading" delay={.15} y={40}><h1 className="hero-heading" id="hero-title">Hi, I'm Saad</h1></FadeIn></div><p className="hero-role"><T en="PRODUCT OWNER · BUSINESS ENGINEER · QUALITY ENGINEER" fr="PRODUCT OWNER · INGÉNIEUR D’AFFAIRES · INGÉNIEUR QUALITÉ"/></p><div className="creator-portrait"><div className="portrait-scroll-zoom"><FadeIn delay={.15} fade={false}><Magnet><div className="portrait-frame"><img src="assets/saad-portrait.webp" srcSet="assets/saad-portrait-420.webp 420w, assets/saad-portrait.webp 800w" sizes="(max-width:640px) 250px, 400px" alt="Saad Bayahia" width="800" height="1000" {...{fetchpriority:"high"}} decoding="async"/><div className="portrait-signature"><span>SAAD BAYAHIA</span><span>PARIS, FR</span></div></div></Magnet></FadeIn></div></div><div ref={actions} className="creator-hero-bottom"><FadeIn delay={.35}><p className="creator-hero-statement"><T en="I turn complex business challenges into connected products that work." fr="Je transforme les défis métier en produits utiles et systèmes connectés."/></p><aside className="hero-profile" aria-label="About Saad Bayahia"><span className="availability-dot"/><span><T en="Paris, France · Open to new opportunities" fr="Paris, France · Ouvert à de nouvelles opportunités"/></span></aside></FadeIn><a href="#about" className="creator-scroll" aria-label="Explore the portfolio"><ArrowDown size={20} aria-hidden="true"/></a><FadeIn delay={.5}><ContactButton/></FadeIn></div><p className="hero-tools-note"><T en="My toolkit, in motion" fr="Mon écosystème, en mouvement"/><span>{toolkit.tools.map(tool=>tool.name).join(" · ")}</span></p><div className="hero-telemetry" hidden aria-hidden="true"><span id="cursor-x"/><span id="cursor-y"/><span id="scroll-position"/></div></section></div><AboutSection/></m.div>;}
const marqueeImages=[
 {src:'assets/creator-ribbon-1-360.webp',srcSet:'assets/creator-ribbon-1-360.webp 360w, assets/creator-ribbon-1-720.webp 640w',alt:'FFA — commerce',href:'#ffa-title'},
 {src:'assets/creator-ribbon-2-360.webp',srcSet:'assets/creator-ribbon-2-360.webp 360w, assets/creator-ribbon-2-720.webp 640w',alt:'LeadHunt — agents IA',href:'#leadhunt-title'},
 {src:'assets/creator-ribbon-3-360.webp',srcSet:'assets/creator-ribbon-3-360.webp 360w, assets/creator-ribbon-3-720.webp 720w',alt:'Cardiag — espace propriétaire',href:'#cardiag-title'},
 {src:'assets/creator-ribbon-4-360.webp',srcSet:'assets/creator-ribbon-4-360.webp 360w, assets/creator-ribbon-4-720.webp 720w',alt:'FFA — Shopify',href:'#ffa-title'},
 {src:'assets/creator-ribbon-5-360.webp',srcSet:'assets/creator-ribbon-5-360.webp 360w, assets/creator-ribbon-5-720.webp 720w',alt:'LeadHunt — cartographie',href:'#leadhunt-title'},
 {src:'assets/creator-ribbon-6-360.webp',srcSet:'assets/creator-ribbon-6-360.webp 360w, assets/creator-ribbon-6-720.webp 445w',alt:'SecoursNow — prototype mobile',href:'#secoursnow-title'},
 {src:'assets/creator-ribbon-7-360.webp',srcSet:'assets/creator-ribbon-7-360.webp 360w, assets/creator-ribbon-7-720.webp 720w',alt:'Cardiag — diagnostic conversationnel',href:'#cardiag-title'},
 {src:'assets/creator-ribbon-8-360.webp',srcSet:'assets/creator-ribbon-8-360.webp 360w, assets/creator-ribbon-8-720.webp 720w',alt:'FFA — Ankorstore',href:'#ffa-title'}
];
function MarqueeRow({items,reverse,progress}:{items:typeof marqueeImages;reverse?:boolean;progress:MotionValue<number>}){
 const {stopped}=useContext(Preferences),x=useTransform(progress,[0,1],reverse?[0,-200]:[-200,0]);
 return <div className="marquee-viewport"><m.div className="creator-marquee-row" style={{x:stopped?0:x}}>{[...items,...items].map((item,i)=><a key={i} className="marquee-tile" href={item.href} aria-hidden={i>=items.length?true:undefined} tabIndex={i>=items.length?-1:undefined}><img src={item.src} srcSet={item.srcSet} sizes="(max-width:640px) 268px, 420px" alt={i>=items.length?'':item.alt} width="420" height="270" loading="lazy" decoding="async"/><span>{item.alt}<ArrowUpRight size={16} aria-hidden="true"/></span></a>)}</m.div></div>;
}
function MarqueeSection(){const ref=useRef<HTMLElement>(null),{scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});return <section id="showcase" ref={ref} className="creator-marquee" aria-label="Project previews"><p className="creator-eyebrow text-center"><T en="REAL PRODUCTS. CONNECTED SYSTEMS." fr="DES PRODUITS CONCRETS. DES SYSTÈMES CONNECTÉS."/></p><MarqueeRow items={marqueeImages.slice(0,4)} progress={scrollYProgress}/><MarqueeRow items={marqueeImages.slice(4)} reverse progress={scrollYProgress}/></section>;}
function AnimatedText(){const ref=useRef<HTMLParagraphElement>(null),{fr,stopped}=useContext(Preferences),{scrollYProgress}=useScroll({target:ref,offset:['start .8','end .2']});const text=fr?'Product Owner, Business Engineer et Quality Engineer. Je relie vision produit, développement commercial et rigueur industrielle. Prospection B2B, vente complexe et négociation nourrissent ma compréhension des besoins ; analyse des risques et amélioration continue guident la réalisation de solutions utiles et fiables.':'Product Owner, Business Engineer and Quality Engineer. I connect product vision, business development and industrial discipline. B2B prospecting, complex sales and negotiation shape my understanding of customer needs; risk analysis and continuous improvement guide the delivery of useful, reliable solutions.';let count=0;return <m.p ref={ref} className="animated-profile-text" style={{'--reveal-progress':stopped?1:scrollYProgress} as React.CSSProperties & {'--reveal-progress':number|MotionValue<number>}}><span className="sr-only">{text}</span>{text.split(' ').map((word,i)=><span key={i} className="animated-text-word" aria-hidden="true">{[...word].map((char,j)=>{const index=count++;return <Character key={j} index={index} total={text.length} stopped={stopped}>{char}</Character>;})}{' '}</span>)}</m.p>;}
// One motion value updates the paragraph; CSS interpolates each character without hundreds of subscriptions.
function Character({index,total,stopped,children}:{index:number;total:number;stopped:boolean;children:ReactNode}){return <span style={{opacity:stopped?1:`clamp(.65, calc((var(--reveal-progress, 0) - ${index/total}) * ${total*.35/14} + .65), 1)`}}>{children}</span>;}
function AboutSection(){return <section id="about" className="creator-about" aria-labelledby="about-title"><div className="about-orbit orbit-one" aria-hidden="true"><Orbit/></div><div className="about-orbit orbit-two" aria-hidden="true"><Box/></div><div className="about-orbit orbit-three" aria-hidden="true"><Layers3/></div><div className="about-orbit orbit-four" aria-hidden="true"><Workflow/></div><div className="about-title-reveal"><h2 id="about-title" className="hero-heading creator-section-title"><T en="About me" fr="À propos"/></h2></div><div className="about-content"><AnimatedText/><div className="profile-facts"><span><strong>20+</strong><T en="Shopify stores" fr="boutiques Shopify"/></span><span><strong>6 <small><T en="years" fr="ans"/></small></strong><T en="industrial quality" fr="qualité industrielle"/></span><span><strong>KEDGE</strong><T en="MSc Business Engineering" fr="MSc Ingénierie d’Affaires"/></span></div><div className="profile-links"><a href="#journey"><T en="Explore my career" fr="Voir mon parcours"/><ArrowUpRight size={16} aria-hidden="true"/></a><a href="https://drive.google.com/file/d/1Zjdm9HVKVVuJrldlYEMhyOy04RaKGhzf/view?usp=sharing" target="_blank" rel="noopener noreferrer"><T en="View my CV" fr="Voir mon CV"/><ArrowUpRight size={16} aria-hidden="true"/></a><a href="https://www.linkedin.com/in/saad-bayahia-2b025916a/" target="_blank" rel="noopener noreferrer">LinkedIn<ArrowUpRight size={16} aria-hidden="true"/></a></div><nav className="profile-chapters" aria-label="Explore more / Aller plus loin"><a href="#method"><T en="My approach" fr="Ma méthode"/><ArrowUpRight size={16} aria-hidden="true"/></a><a href="#international"><T en="Languages & mobility" fr="Langues & mobilité"/><ArrowUpRight size={16} aria-hidden="true"/></a><a href="#beyond"><T en="Beyond work" fr="Hors cadre"/><ArrowUpRight size={16} aria-hidden="true"/></a></nav></div></section>;}
const services=[
 ['Product strategy','Stratégie produit','Discovery, roadmaps, prioritisation and cross-functional delivery. Turning user needs into clear specifications and measurable releases.','Discovery, roadmap, priorisation et delivery transverse. Transformer les besoins en spécifications claires et en résultats mesurables.'],
 ['Business engineering','Ingénierie d’affaires','B2B prospecting, needs qualification, complex sales and negotiation. Building value propositions, coordinating stakeholders and developing long-term customer relationships.','Prospection B2B, qualification des besoins, vente complexe et négociation. Construire des propositions de valeur, coordonner les décideurs et développer des relations clients durables.'],
 ['Commerce & B2B','E-commerce & B2B','Shopify Plus platforms, wholesale journeys and marketplace ecosystems. One connected experience from the catalogue to fulfilment.','Plateformes Shopify Plus, parcours grossistes et écosystèmes marketplace. Une expérience connectée du catalogue à l’expédition.'],
 ['Automation & integrations','Automatisation & intégrations','APIs, webhooks and n8n workflows connecting ERP, CRM, logistics and invoicing. Less repetitive work, more reliable operations.','API, webhooks et workflows n8n reliant ERP, CRM, logistique et facturation. Moins de saisie répétitive, des opérations plus fiables.'],
 ['Applied AI & tools','IA appliquée & outils','Prospecting assistants, customer-support knowledge bases and purpose-built web tools. Practical AI anchored in real workflows.','Assistants de prospection, bases de connaissances du support client et outils web métier. Une IA ancrée dans les usages concrets.'],
 ['Quality engineering','Ingénierie qualité','Risk analysis, FMEA, root-cause investigation and corrective actions. 8D, PDCA and lessons learned support continuous improvement, informed by ISO 9001 and IATF 16949 frameworks.','Analyse des risques, AMDEC, recherche des causes racines et actions correctives. 8D, PDCA et RETEX soutiennent l’amélioration continue, avec la pratique des référentiels ISO 9001 et IATF 16949.']
];
function ServicesSection(){return <section id="services" className="creator-services" aria-labelledby="services-title"><p className="creator-eyebrow text-center"><T en="HOW I CAN CONTRIBUTE" fr="CE QUE JE PEUX APPORTER"/></p><FadeIn><h2 id="services-title" className="creator-section-title"><T en="Expertise" fr="Expertises"/></h2></FadeIn><div className="services-list">{services.map(([en,fr,description,descriptionFr],i)=><FadeIn key={en} delay={i*.08}><article className="service-item"><span className="service-number" aria-hidden="true">{String(i+1).padStart(2,'0')}</span><div><h3><T en={en} fr={fr}/></h3><p><T en={description} fr={descriptionFr}/></p></div><ArrowUpRight className="service-arrow" size={28} aria-hidden="true"/></article></FadeIn>)}<Native html={content.skills}/></div></section>;}
function ProjectCard({project,index,total=content.projects.length,career=false}:{project:{id:string;html:string};index:number;total?:number;career?:boolean}){const ref=useRef<HTMLDivElement>(null),{stopped}=useContext(Preferences),{scrollYProgress}=useScroll({target:ref,offset:['start start','start -1']}),scale=useTransform(scrollYProgress,[0,1],[1,1-Math.min(2,total-1-index)*.03]);return <><div ref={ref} className="project-marker" aria-hidden="true"/><m.article id={project.id} className={'creator-project project project-'+project.id+(career?' journey-card':'')} aria-labelledby={project.id+'-title'} style={{top:"var(--stack-top, 96px)","--stack-rest-top":96+Math.min(index,2)*16,scale:stopped?1:scale,zIndex:index+1} as React.CSSProperties}><Native html={career?project.html.replace('{{journeyNumber}}',String(index+1).padStart(2,'0')):project.html}/></m.article></>;}
function ProjectDirectory(){const {fr}=useContext(Preferences);return <details className="project-directory"><summary><span>{fr?'Choisir un projet':'Choose a project'}</span><span className="project-directory-count">{content.projects.length} <span aria-hidden="true">+</span></span></summary><nav aria-label={fr?'Sommaire des projets':'Project directory'}><ol>{content.projects.map((project,index)=><li key={project.id}><a href={'#'+project.id+'-title'}><span className="directory-number" aria-hidden="true">{String(index+1).padStart(2,'0')}</span><span>{fr?project.indexLabel.fr:project.indexLabel.en}</span><ArrowUpRight size={16} aria-hidden="true"/></a></li>)}</ol></nav></details>;}
function ProjectsSection(){return <section id="work" className="creator-projects" aria-labelledby="work-title"><svg className="logo-filter-definitions" aria-hidden="true" width="0" height="0"><defs><filter id="logo-remove-white" colorInterpolationFilters="sRGB"><feColorMatrix type="matrix" values="0 0 0 0 .78 0 0 0 0 .78 0 0 0 0 .78 -.666 -.666 -.666 0 2"/><feComposite in2="SourceGraphic" operator="in"/></filter><filter id="logo-dark-symbol" colorInterpolationFilters="sRGB"><feColorMatrix type="matrix" values="0 0 0 0 .78 0 0 0 0 .78 0 0 0 0 .78 -.5 -.5 0 0 1"/><feComposite in2="SourceGraphic" operator="in"/></filter><filter id="logo-light-symbol" colorInterpolationFilters="sRGB"><feColorMatrix type="matrix" values="0 0 0 0 .78 0 0 0 0 .78 0 0 0 0 .78 0 4 0 0 -3"/><feComposite in2="SourceGraphic" operator="in"/></filter></defs></svg><div className="creator-work-heading"><p className="creator-eyebrow"><T en="PRODUCT / COMMERCE / ENGINEERING" fr="PRODUIT / COMMERCE / INGÉNIERIE"/></p><FadeIn><h2 id="work-title" className="hero-heading creator-section-title"><T en="Projects" fr="Projets"/></h2></FadeIn><p><T en="Product thinking. Engineering depth. Real-world impact." fr="La vision produit. La profondeur technique. L’impact terrain."/></p></div><ProjectDirectory/><div className="project-stack">{content.projects.map((project,index)=><ProjectCard key={project.id} project={project} index={index}/>)}</div></section>;}
function JourneySection(){
 return <section id="journey" className="creator-projects creator-journey" aria-labelledby="journey-title">
  <div className="creator-work-heading">
   <p className="creator-eyebrow"><T en="EXPERIENCE / EDUCATION / CONTINUING DEVELOPMENT" fr="EXPÉRIENCES / FORMATIONS / FORMATION CONTINUE"/></p>
   <FadeIn><h2 id="journey-title" className="hero-heading creator-section-title"><T en="Career" fr="Parcours"/></h2></FadeIn>
   <p><T en="Quality engineering, business development and product ownership." fr="Ingénierie qualité, développement d’affaires et pilotage produit."/></p>
   <nav className="journey-navigation" aria-label="Career / Parcours">
    {journey.map(group=><a key={group.id} href={'#'+group.id}>{group.kind==='experience'?<T en="Experience" fr="Expériences"/>:group.kind==='education'?<T en="Education" fr="Formations"/>:<T en="Certifications" fr="Certifications"/>}<span className="journey-count">{String(group.recordCount??group.entries.length).padStart(2,'0')}</span></a>)}
   </nav>
  </div>
  {journey.map((group,groupIndex)=><div key={group.id} id={group.id} className="journey-group" role="group" aria-labelledby={group.id+'-heading'}>
   <div className="journey-group-header">
    <span aria-hidden="true">{String(groupIndex+1).padStart(2,'0')} / {String(journey.length).padStart(2,'0')}</span>
    <p id={group.id+'-heading'}>{group.kind==='experience'?<T en="Professional experience" fr="Expériences professionnelles"/>:group.kind==='education'?<T en="Education & qualifications" fr="Formations & diplômes"/>:<T en="Certifications & continuing education" fr="Certifications & formation continue"/>}</p>
   </div>
   {group.entries.length>1&&<nav className="journey-index" aria-label={group.kind==='experience'?'Choose an experience / Choisir une expérience':'Choose an education path / Choisir une formation'}>
    <ol>{group.entries.map((entry,index)=><li key={entry.id}><a href={'#'+entry.id+'-title'}><span className="journey-index-number" aria-hidden="true">{String(index+1).padStart(2,'0')}</span><span>{entry.label}</span><ArrowUpRight size={16} aria-hidden="true"/></a></li>)}</ol>
   </nav>}
   <div className="project-stack">{group.entries.map((entry,index)=><ProjectCard key={entry.id} project={entry} index={index} total={group.entries.length} career/>)}</div>
  </div>)}
 </section>;
}
function ProductMethod(){return <MethodSection {...useContext(Preferences)}/>;}
function InternationalProfile(){return <InternationalSection {...useContext(Preferences)}/>;}
function BeyondWork(){return <BeyondSection {...useContext(Preferences)}/>;}
export function App(){return <PreferencesProvider><LazyMotion features={domAnimation}><div className="creator-page overflow-x-clip"><a className="skip-link" href="#main">Skip to content</a><Header/><main id="main" tabIndex={-1}><HeroSection/><MarqueeSection/><ServicesSection/><ProductMethod/><ProjectsSection/><JourneySection/><InternationalProfile/><BeyondWork/><Native html={content.contact}/></main><Native html={content.footer}/><Native html={content.dialog}/><div className="image-cursor" aria-hidden="true"><span data-i18n="cursorViewImage">VIEW IMAGE</span><span>↗</span></div></div></LazyMotion></PreferencesProvider>;}
